/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graph;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edho
 */
public class GrafBonus extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    static ImageIcon Cross, Warning, Plus, Check, OneWay, TwoWay;
    public GrafBonus() {
        initComponents();
        Cross = new javax.swing.ImageIcon(getClass().getResource("/Assets/Cross.png"));
        Warning = new javax.swing.ImageIcon(getClass().getResource("/Assets/Warning.png"));
        Plus = new javax.swing.ImageIcon(getClass().getResource("/Assets/Plus.png"));
        Check = new javax.swing.ImageIcon(getClass().getResource("/Assets/Check.png"));
        OneWay = new javax.swing.ImageIcon(getClass().getResource("/Assets/OneWay.png"));
        TwoWay = new javax.swing.ImageIcon(getClass().getResource("/Assets/TwoWay.png"));
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        panelBody = new javax.swing.JPanel();
        panelAwal = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblSubJudul = new javax.swing.JLabel();
        txtInputSimpulPertama = new javax.swing.JTextField();
        lblInputSimpulPertama = new javax.swing.JLabel();
        shInputSimpulPertama = new javax.swing.JLabel();
        btnMulai = new javax.swing.JButton();
        shBtnMulai = new javax.swing.JLabel();
        panelTutorial = new javax.swing.JPanel();
        btnSimpulTutorial = new javax.swing.JButton();
        shBtnSimpulTutorial = new javax.swing.JLabel();
        btnSisiTutorial = new javax.swing.JButton();
        shBtnSisiTutorial = new javax.swing.JLabel();
        btnJarakTutorial = new javax.swing.JButton();
        shBtnJarakTutorial = new javax.swing.JLabel();
        lblJudulTutorial = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelSimpul = new javax.swing.JPanel();
        btnTambahSimpul = new javax.swing.JButton();
        shBtnTambahSimpul = new javax.swing.JLabel();
        txtSimpulBaru = new javax.swing.JTextField();
        lblSimpulBaru = new javax.swing.JLabel();
        shLblSimpulBaru = new javax.swing.JLabel();
        cmbxLihatSimpul = new javax.swing.JComboBox<>();
        lblInputSimpul = new javax.swing.JLabel();
        lblJudulSimpul = new javax.swing.JLabel();
        lblJudulBuatSimpul = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaInfoSimpul = new javax.swing.JTextArea();
        lblInfoSimpul = new javax.swing.JLabel();
        shInfoSimpul = new javax.swing.JLabel();
        panelSisi = new javax.swing.JPanel();
        cmbxTitikAwal = new javax.swing.JComboBox<>();
        cmbxTitikAkhir = new javax.swing.JComboBox<>();
        lblAwal = new javax.swing.JLabel();
        lblAkhir = new javax.swing.JLabel();
        btnTambahSisi = new javax.swing.JButton();
        shBtnTambahSisi = new javax.swing.JLabel();
        txtInputJarak = new javax.swing.JTextField();
        lblJudulSisi = new javax.swing.JLabel();
        ToggleDuaArah = new javax.swing.JToggleButton();
        shToggleOneWay = new javax.swing.JLabel();
        lblJarak = new javax.swing.JLabel();
        lblInputJarak = new javax.swing.JLabel();
        shLblInputJarak = new javax.swing.JLabel();
        panelJarak = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaInfoJarak = new javax.swing.JTextArea();
        lblJudulJarak = new javax.swing.JLabel();
        lblInfoJarak = new javax.swing.JLabel();
        shInfoJarak = new javax.swing.JLabel();
        cmbxStart = new javax.swing.JComboBox<>();
        cmbxEnd = new javax.swing.JComboBox<>();
        lblStart = new javax.swing.JLabel();
        lblEnd = new javax.swing.JLabel();
        shBody = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        shBtnExit = new javax.swing.JLabel();
        btnMoveBonus = new javax.swing.JButton();
        shBtnMoveBonus = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        shBtnBack = new javax.swing.JLabel();
        btnSimpul = new javax.swing.JButton();
        shBtnSimpul = new javax.swing.JLabel();
        btnSisi = new javax.swing.JButton();
        shBtnSisi = new javax.swing.JLabel();
        btnJarak = new javax.swing.JButton();
        shBtnJarak = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();
        shBtnHelp = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBody.setBackground(new java.awt.Color(158, 206, 154));
        panelBody.setLayout(new java.awt.CardLayout());

        panelAwal.setBackground(new java.awt.Color(0, 83, 119));
        panelAwal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudul.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("CREATE-A-GRAPH");
        panelAwal.add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 840, -1));

        lblSubJudul.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblSubJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblSubJudul.setText("Buat simpul pertamamu!");
        panelAwal.add(lblSubJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        txtInputSimpulPertama.setBackground(new java.awt.Color(184, 243, 255));
        txtInputSimpulPertama.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        txtInputSimpulPertama.setText("Masukkan nama simpul...");
        txtInputSimpulPertama.setBorder(null);
        txtInputSimpulPertama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputSimpulPertamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputSimpulPertamaFocusLost(evt);
            }
        });
        txtInputSimpulPertama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputSimpulPertamaActionPerformed(evt);
            }
        });
        txtInputSimpulPertama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInputSimpulPertamaKeyReleased(evt);
            }
        });
        panelAwal.add(txtInputSimpulPertama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 275, 550, 50));

        lblInputSimpulPertama.setBackground(new java.awt.Color(184, 243, 255));
        lblInputSimpulPertama.setOpaque(true);
        panelAwal.add(lblInputSimpulPertama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 590, 60));

        shInputSimpulPertama.setBackground(new java.awt.Color(138, 198, 208));
        shInputSimpulPertama.setOpaque(true);
        panelAwal.add(shInputSimpulPertama, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 275, 590, 60));

        btnMulai.setBackground(new java.awt.Color(104, 170, 186));
        btnMulai.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnMulai.setForeground(new java.awt.Color(255, 255, 255));
        btnMulai.setText("NAMA TIDAK BOLEH KOSONG");
        btnMulai.setContentAreaFilled(false);
        btnMulai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMulai.setEnabled(false);
        btnMulai.setOpaque(true);
        btnMulai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMulaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMulaiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMulaiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMulaiMouseReleased(evt);
            }
        });
        btnMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulaiActionPerformed(evt);
            }
        });
        panelAwal.add(btnMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 240, 60));

        shBtnMulai.setBackground(new java.awt.Color(69, 141, 164));
        shBtnMulai.setOpaque(true);
        panelAwal.add(shBtnMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 355, 240, 60));

        panelBody.add(panelAwal, "splash");

        panelTutorial.setBackground(new java.awt.Color(0, 83, 119));
        panelTutorial.setToolTipText("");
        panelTutorial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSimpulTutorial.setBackground(new java.awt.Color(158, 206, 154));
        btnSimpulTutorial.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnSimpulTutorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Simpul.png"))); // NOI18N
        btnSimpulTutorial.setText("SIMPUL");
        btnSimpulTutorial.setContentAreaFilled(false);
        btnSimpulTutorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpulTutorial.setMargin(new java.awt.Insets(2, 10, 2, 14));
        btnSimpulTutorial.setOpaque(true);
        btnSimpulTutorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimpulTutorialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimpulTutorialMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSimpulTutorialMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSimpulTutorialMouseReleased(evt);
            }
        });
        btnSimpulTutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpulTutorialActionPerformed(evt);
            }
        });
        panelTutorial.add(btnSimpulTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 200, 100));

        shBtnSimpulTutorial.setBackground(new java.awt.Color(108, 153, 118));
        shBtnSimpulTutorial.setOpaque(true);
        panelTutorial.add(shBtnSimpulTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 135, 200, 100));

        btnSisiTutorial.setBackground(new java.awt.Color(158, 206, 154));
        btnSisiTutorial.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnSisiTutorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Sisi.png"))); // NOI18N
        btnSisiTutorial.setText("SISI");
        btnSisiTutorial.setContentAreaFilled(false);
        btnSisiTutorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSisiTutorial.setMargin(new java.awt.Insets(2, 10, 2, 14));
        btnSisiTutorial.setOpaque(true);
        btnSisiTutorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSisiTutorialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSisiTutorialMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSisiTutorialMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSisiTutorialMouseReleased(evt);
            }
        });
        btnSisiTutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSisiTutorialActionPerformed(evt);
            }
        });
        panelTutorial.add(btnSisiTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 200, 100));

        shBtnSisiTutorial.setBackground(new java.awt.Color(108, 153, 118));
        shBtnSisiTutorial.setOpaque(true);
        panelTutorial.add(shBtnSisiTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 285, 200, 100));

        btnJarakTutorial.setBackground(new java.awt.Color(158, 206, 154));
        btnJarakTutorial.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnJarakTutorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Curve.png"))); // NOI18N
        btnJarakTutorial.setText("CEK JARAK");
        btnJarakTutorial.setContentAreaFilled(false);
        btnJarakTutorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJarakTutorial.setMargin(new java.awt.Insets(2, 2, 2, 6));
        btnJarakTutorial.setOpaque(true);
        btnJarakTutorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnJarakTutorialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnJarakTutorialMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnJarakTutorialMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnJarakTutorialMouseReleased(evt);
            }
        });
        btnJarakTutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJarakTutorialActionPerformed(evt);
            }
        });
        panelTutorial.add(btnJarakTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 200, 100));

        shBtnJarakTutorial.setBackground(new java.awt.Color(108, 153, 118));
        shBtnJarakTutorial.setOpaque(true);
        panelTutorial.add(shBtnJarakTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 435, 200, 100));

        lblJudulTutorial.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        lblJudulTutorial.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulTutorial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulTutorial.setText("SELANJUTNYA...");
        panelTutorial.add(lblJudulTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 840, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>Cek jarak dari satu simpul ke simpul lainnya <br> serta menampilkan lintasan yang dilewati</html>");
        panelTutorial.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 420, 90));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html>Buat simpul baru serta cek keterhubungan antara <br> satu simpul dengan simpul lainnya</html>");
        panelTutorial.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 420, 90));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<html>Buat atau ubah sisi yang menghubungkan satu <br> simpul dengan simpul lainnya</html>");
        panelTutorial.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 420, 90));

        panelBody.add(panelTutorial, "next");

        panelSimpul.setBackground(new java.awt.Color(0, 83, 119));
        panelSimpul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTambahSimpul.setBackground(new java.awt.Color(104, 170, 186));
        btnTambahSimpul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Plus.png"))); // NOI18N
        btnTambahSimpul.setContentAreaFilled(false);
        btnTambahSimpul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahSimpul.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Cross.png"))); // NOI18N
        btnTambahSimpul.setEnabled(false);
        btnTambahSimpul.setOpaque(true);
        btnTambahSimpul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahSimpulMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahSimpulMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTambahSimpulMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTambahSimpulMouseReleased(evt);
            }
        });
        btnTambahSimpul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahSimpulActionPerformed(evt);
            }
        });
        panelSimpul.add(btnTambahSimpul, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 60, 60));

        shBtnTambahSimpul.setBackground(new java.awt.Color(69, 141, 164));
        shBtnTambahSimpul.setOpaque(true);
        panelSimpul.add(shBtnTambahSimpul, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 135, 60, 60));

        txtSimpulBaru.setBackground(new java.awt.Color(184, 243, 255));
        txtSimpulBaru.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        txtSimpulBaru.setText("Masukkan nama simpul...");
        txtSimpulBaru.setBorder(null);
        txtSimpulBaru.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSimpulBaruFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSimpulBaruFocusLost(evt);
            }
        });
        txtSimpulBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSimpulBaruActionPerformed(evt);
            }
        });
        txtSimpulBaru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSimpulBaruKeyReleased(evt);
            }
        });
        panelSimpul.add(txtSimpulBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 135, 440, 50));

        lblSimpulBaru.setBackground(new java.awt.Color(184, 243, 255));
        lblSimpulBaru.setOpaque(true);
        panelSimpul.add(lblSimpulBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 480, 60));

        shLblSimpulBaru.setBackground(new java.awt.Color(138, 198, 208));
        shLblSimpulBaru.setOpaque(true);
        panelSimpul.add(shLblSimpulBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 135, 480, 60));

        cmbxLihatSimpul.setBackground(new java.awt.Color(184, 243, 255));
        cmbxLihatSimpul.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        cmbxLihatSimpul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxLihatSimpulActionPerformed(evt);
            }
        });
        panelSimpul.add(cmbxLihatSimpul, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 470, 60));

        lblInputSimpul.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        lblInputSimpul.setForeground(new java.awt.Color(255, 255, 255));
        lblInputSimpul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInputSimpul.setText("CEK HUBUNGAN");
        panelSimpul.add(lblInputSimpul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 300, 60));

        lblJudulSimpul.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        lblJudulSimpul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulSimpul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulSimpul.setText("SIMPUL (VERTICE)");
        panelSimpul.add(lblJudulSimpul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 840, -1));

        lblJudulBuatSimpul.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        lblJudulBuatSimpul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulBuatSimpul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulBuatSimpul.setText("BUAT");
        panelSimpul.add(lblJudulBuatSimpul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 132, 200, 60));

        areaInfoSimpul.setEditable(false);
        areaInfoSimpul.setBackground(new java.awt.Color(184, 243, 255));
        areaInfoSimpul.setColumns(20);
        areaInfoSimpul.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        areaInfoSimpul.setRows(5);
        areaInfoSimpul.setBorder(null);
        areaInfoSimpul.setCaretColor(new java.awt.Color(184, 243, 255));
        jScrollPane1.setViewportView(areaInfoSimpul);

        panelSimpul.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 670, 200));

        lblInfoSimpul.setBackground(new java.awt.Color(184, 243, 255));
        lblInfoSimpul.setOpaque(true);
        panelSimpul.add(lblInfoSimpul, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 710, 240));

        shInfoSimpul.setBackground(new java.awt.Color(138, 198, 208));
        shInfoSimpul.setOpaque(true);
        panelSimpul.add(shInfoSimpul, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 355, 710, 240));

        panelBody.add(panelSimpul, "simpul");

        panelSisi.setBackground(new java.awt.Color(0, 83, 119));
        panelSisi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbxTitikAwal.setBackground(new java.awt.Color(184, 243, 255));
        cmbxTitikAwal.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        cmbxTitikAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxTitikAwalActionPerformed(evt);
            }
        });
        panelSisi.add(cmbxTitikAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 190, 50));

        cmbxTitikAkhir.setBackground(new java.awt.Color(184, 243, 255));
        cmbxTitikAkhir.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        cmbxTitikAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxTitikAkhirActionPerformed(evt);
            }
        });
        panelSisi.add(cmbxTitikAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 190, 50));

        lblAwal.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblAwal.setForeground(new java.awt.Color(255, 255, 255));
        lblAwal.setText("SIMPUL AWAL");
        panelSisi.add(lblAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 190, 40));

        lblAkhir.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblAkhir.setForeground(new java.awt.Color(255, 255, 255));
        lblAkhir.setText("SIMPUL AKHIR");
        panelSisi.add(lblAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 190, 40));

        btnTambahSisi.setBackground(new java.awt.Color(104, 170, 186));
        btnTambahSisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Edit.png"))); // NOI18N
        btnTambahSisi.setContentAreaFilled(false);
        btnTambahSisi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahSisi.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Cross.png"))); // NOI18N
        btnTambahSisi.setEnabled(false);
        btnTambahSisi.setOpaque(true);
        btnTambahSisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahSisiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahSisiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTambahSisiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTambahSisiMouseReleased(evt);
            }
        });
        btnTambahSisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahSisiActionPerformed(evt);
            }
        });
        panelSisi.add(btnTambahSisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 70, 70));

        shBtnTambahSisi.setBackground(new java.awt.Color(69, 141, 164));
        shBtnTambahSisi.setOpaque(true);
        panelSisi.add(shBtnTambahSisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 365, 70, 70));

        txtInputJarak.setEditable(false);
        txtInputJarak.setBackground(new java.awt.Color(184, 243, 255));
        txtInputJarak.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        txtInputJarak.setText("JARAK TIDAK ADA");
        txtInputJarak.setBorder(null);
        txtInputJarak.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputJarakFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputJarakFocusLost(evt);
            }
        });
        txtInputJarak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputJarakActionPerformed(evt);
            }
        });
        txtInputJarak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInputJarakKeyReleased(evt);
            }
        });
        panelSisi.add(txtInputJarak, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 365, 380, 50));

        lblJudulSisi.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        lblJudulSisi.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulSisi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulSisi.setText("SISI");
        panelSisi.add(lblJudulSisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 840, -1));

        ToggleDuaArah.setBackground(new java.awt.Color(184, 243, 255));
        ToggleDuaArah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/TwoWay.png"))); // NOI18N
        ToggleDuaArah.setSelected(true);
        ToggleDuaArah.setContentAreaFilled(false);
        ToggleDuaArah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ToggleDuaArah.setOpaque(true);
        ToggleDuaArah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleDuaArahActionPerformed(evt);
            }
        });
        panelSisi.add(ToggleDuaArah, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 50, 50));

        shToggleOneWay.setBackground(new java.awt.Color(138, 198, 208));
        shToggleOneWay.setOpaque(true);
        panelSisi.add(shToggleOneWay, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 225, 50, 50));

        lblJarak.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblJarak.setForeground(new java.awt.Color(255, 255, 255));
        lblJarak.setText("JARAK");
        panelSisi.add(lblJarak, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, 40));

        lblInputJarak.setBackground(new java.awt.Color(184, 243, 255));
        lblInputJarak.setOpaque(true);
        panelSisi.add(lblInputJarak, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 420, 60));

        shLblInputJarak.setBackground(new java.awt.Color(138, 198, 208));
        shLblInputJarak.setOpaque(true);
        panelSisi.add(shLblInputJarak, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 365, 420, 60));

        panelBody.add(panelSisi, "sisi");

        panelJarak.setBackground(new java.awt.Color(0, 83, 119));
        panelJarak.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        areaInfoJarak.setEditable(false);
        areaInfoJarak.setBackground(new java.awt.Color(184, 243, 255));
        areaInfoJarak.setColumns(20);
        areaInfoJarak.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        areaInfoJarak.setRows(5);
        areaInfoJarak.setBorder(null);
        areaInfoJarak.setCaretColor(new java.awt.Color(184, 243, 255));
        jScrollPane2.setViewportView(areaInfoJarak);

        panelJarak.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 670, 240));

        lblJudulJarak.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        lblJudulJarak.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulJarak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulJarak.setText("CEK JARAK ANTARA DUA SIMPUL");
        panelJarak.add(lblJudulJarak, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 850, 50));

        lblInfoJarak.setBackground(new java.awt.Color(184, 243, 255));
        lblInfoJarak.setOpaque(true);
        panelJarak.add(lblInfoJarak, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 710, 280));

        shInfoJarak.setBackground(new java.awt.Color(138, 198, 208));
        shInfoJarak.setOpaque(true);
        panelJarak.add(shInfoJarak, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 315, 710, 280));

        cmbxStart.setBackground(new java.awt.Color(184, 243, 255));
        cmbxStart.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        cmbxStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxStartActionPerformed(evt);
            }
        });
        panelJarak.add(cmbxStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 300, 50));

        cmbxEnd.setBackground(new java.awt.Color(184, 243, 255));
        cmbxEnd.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        cmbxEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxEndActionPerformed(evt);
            }
        });
        panelJarak.add(cmbxEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 300, 50));

        lblStart.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblStart.setForeground(new java.awt.Color(255, 255, 255));
        lblStart.setText("TITIK AWAL");
        panelJarak.add(lblStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 300, 40));

        lblEnd.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblEnd.setForeground(new java.awt.Color(255, 255, 255));
        lblEnd.setText("TITIK AKHIR");
        panelJarak.add(lblEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 300, 40));

        panelBody.add(panelJarak, "jarak");

        getContentPane().add(panelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 840, 630));

        shBody.setBackground(new java.awt.Color(5, 47, 95));
        shBody.setOpaque(true);
        getContentPane().add(shBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 840, 630));

        btnExit.setBackground(new java.awt.Color(255, 60, 0));
        btnExit.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Cross.png"))); // NOI18N
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExitMouseReleased(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 50, 50));

        shBtnExit.setBackground(new java.awt.Color(158, 37, 0));
        shBtnExit.setOpaque(true);
        getContentPane().add(shBtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 5, 50, 50));

        btnMoveBonus.setBackground(new java.awt.Color(240, 215, 97));
        btnMoveBonus.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnMoveBonus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Move.png"))); // NOI18N
        btnMoveBonus.setContentAreaFilled(false);
        btnMoveBonus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMoveBonus.setOpaque(true);
        btnMoveBonus.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnMoveBonusMouseDragged(evt);
            }
        });
        btnMoveBonus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMoveBonusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMoveBonusMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMoveBonusMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMoveBonusMouseReleased(evt);
            }
        });
        getContentPane().add(btnMoveBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 50, 50));

        shBtnMoveBonus.setBackground(new java.awt.Color(151, 136, 61));
        shBtnMoveBonus.setOpaque(true);
        getContentPane().add(shBtnMoveBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 5, 50, 50));

        btnBack.setBackground(new java.awt.Color(240, 215, 97));
        btnBack.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/BackArrow.png"))); // NOI18N
        btnBack.setText("KEMBALI");
        btnBack.setContentAreaFilled(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setMargin(new java.awt.Insets(2, 0, 2, 4));
        btnBack.setOpaque(true);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackMouseReleased(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 140, 50));

        shBtnBack.setBackground(new java.awt.Color(151, 136, 61));
        shBtnBack.setOpaque(true);
        getContentPane().add(shBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 5, 140, 50));

        btnSimpul.setBackground(new java.awt.Color(158, 206, 154));
        btnSimpul.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnSimpul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Simpul.png"))); // NOI18N
        btnSimpul.setText("SIMPUL");
        btnSimpul.setContentAreaFilled(false);
        btnSimpul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpul.setMargin(new java.awt.Insets(2, 10, 2, 14));
        btnSimpul.setOpaque(true);
        btnSimpul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimpulMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimpulMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSimpulMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSimpulMouseReleased(evt);
            }
        });
        btnSimpul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpulActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        shBtnSimpul.setBackground(new java.awt.Color(108, 153, 118));
        shBtnSimpul.setOpaque(true);
        getContentPane().add(shBtnSimpul, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 150, 50));

        btnSisi.setBackground(new java.awt.Color(158, 206, 154));
        btnSisi.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnSisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Sisi.png"))); // NOI18N
        btnSisi.setText("SISI");
        btnSisi.setContentAreaFilled(false);
        btnSisi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSisi.setMargin(new java.awt.Insets(2, 10, 2, 14));
        btnSisi.setOpaque(true);
        btnSisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSisiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSisiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSisiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSisiMouseReleased(evt);
            }
        });
        btnSisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSisiActionPerformed(evt);
            }
        });
        getContentPane().add(btnSisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 150, 50));

        shBtnSisi.setBackground(new java.awt.Color(108, 153, 118));
        shBtnSisi.setOpaque(true);
        getContentPane().add(shBtnSisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 5, 150, 50));

        btnJarak.setBackground(new java.awt.Color(158, 206, 154));
        btnJarak.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnJarak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Curve.png"))); // NOI18N
        btnJarak.setText("CEK JARAK");
        btnJarak.setContentAreaFilled(false);
        btnJarak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJarak.setMargin(new java.awt.Insets(2, 2, 2, 6));
        btnJarak.setOpaque(true);
        btnJarak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnJarakMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnJarakMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnJarakMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnJarakMouseReleased(evt);
            }
        });
        btnJarak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJarakActionPerformed(evt);
            }
        });
        getContentPane().add(btnJarak, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 150, 50));

        shBtnJarak.setBackground(new java.awt.Color(108, 153, 118));
        shBtnJarak.setOpaque(true);
        getContentPane().add(shBtnJarak, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 5, 150, 50));

        btnHelp.setBackground(new java.awt.Color(158, 206, 154));
        btnHelp.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Help.png"))); // NOI18N
        btnHelp.setContentAreaFilled(false);
        btnHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHelp.setOpaque(true);
        btnHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHelpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHelpMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHelpMouseReleased(evt);
            }
        });
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        getContentPane().add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 50, 50));

        shBtnHelp.setBackground(new java.awt.Color(108, 153, 118));
        shBtnHelp.setOpaque(true);
        getContentPane().add(shBtnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 5, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahSimpulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahSimpulActionPerformed
        if(!"".equals(txtSimpulBaru.getText())) {
            Graph.tambahSimpul(txtSimpulBaru.getText());
            GUI.UpdateCombobox();
            txtSimpulBaru.setText("");
            btnTambahSimpul.setIcon(Check);
            GUI.tambahsimpul.restart();
        }
    }//GEN-LAST:event_btnTambahSimpulActionPerformed

    private void cmbxLihatSimpulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxLihatSimpulActionPerformed
        areaInfoSimpul.setText("");
        int idx = cmbxLihatSimpul.getSelectedIndex();
        
        for(int i = 0; i < Graph.jumlahSimpul; i++) {
            if (Graph.adjM.get(idx).get(i) != null && Graph.adjM.get(idx).get(i) != 1000000000) {
                areaInfoSimpul.append("Simpul " + Graph.simpul.get(idx).nama + " terhubung dengan simpul " + Graph.simpul.get(i).nama + " dengan jarak " + Graph.adjM.get(idx).get(i) + "\n");
            }
        }
        if ("".equals(areaInfoSimpul.getText())) {
            areaInfoSimpul.setText("Simpul " + Graph.simpul.get(idx).nama + " tidak memiliki sisi dengan simpul apapun!");
        }
    }//GEN-LAST:event_cmbxLihatSimpulActionPerformed

    private void btnTambahSisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahSisiActionPerformed
        int start = cmbxTitikAwal.getSelectedIndex();
        int end = cmbxTitikAkhir.getSelectedIndex();
        int jrk = Integer.parseInt(txtInputJarak.getText());
        boolean duaarah = ToggleDuaArah.isSelected();
        
        txtInputJarak.setText("");
        if (start != -1 || end != -1) {
            Graph.tambahSisi(0, start, end, jrk, duaarah);
        }
        btnTambahSisi.setEnabled(false);
    }//GEN-LAST:event_btnTambahSisiActionPerformed

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        GUI.DropButton(btnExit, 793);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        GUI.LiftButton(btnExit, 790);
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        GUI.DropButton(btnExit, 795);
        btnExit.setBackground(new Color(210,70,0));
    }//GEN-LAST:event_btnExitMousePressed

    private void btnExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseReleased
        GUI.LiftButton(btnExit, 793);
        btnExit.setBackground(new Color(255,60,0));
    }//GEN-LAST:event_btnExitMouseReleased

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        if (GUI.confirmExit) {
            System.exit(0);
        } else {
            btnExit.setIcon(Warning);
            GUI.confirmExit = true;
            GUI.exitbonus.restart();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        GUI.DropButton(btnBack, 583);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        GUI.LiftButton(btnBack, 580);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMousePressed
        GUI.DropButton(btnBack, 585);
        btnBack.setBackground(GUI.ButtonBgClicked());
    }//GEN-LAST:event_btnBackMousePressed

    private void btnBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseReleased
        GUI.LiftButton(btnBack, 583);
        btnBack.setBackground(GUI.ButtonBgUnclicked());
    }//GEN-LAST:event_btnBackMouseReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Graph.flush();
        Graph.preload();
        Maps main = new Maps();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSimpulMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpulMouseEntered
        GUI.DropButton(btnSimpul, 3);
    }//GEN-LAST:event_btnSimpulMouseEntered

    private void btnSimpulMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpulMouseExited
        GUI.LiftButton(btnSimpul, 0);
    }//GEN-LAST:event_btnSimpulMouseExited

    private void btnSimpulMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpulMousePressed
        GUI.DropButton(btnSimpul, 5);
        btnSimpul.setBackground(GUI.ButtonBgBonusMenuClicked());
    }//GEN-LAST:event_btnSimpulMousePressed

    private void btnSimpulMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpulMouseReleased
        GUI.LiftButton(btnSimpul, 3);
        btnSimpul.setBackground(GUI.ButtonBgBonusMenuUnclicked());
    }//GEN-LAST:event_btnSimpulMouseReleased

    private void btnSimpulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpulActionPerformed
        CardLayout menu = (CardLayout) panelBody.getLayout();
        menu.show(panelBody, "simpul");
    }//GEN-LAST:event_btnSimpulActionPerformed

    private void btnSisiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSisiMouseEntered
        GUI.DropButton(btnSisi, 163);
    }//GEN-LAST:event_btnSisiMouseEntered

    private void btnSisiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSisiMouseExited
        GUI.LiftButton(btnSisi, 160);
    }//GEN-LAST:event_btnSisiMouseExited

    private void btnSisiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSisiMousePressed
        GUI.DropButton(btnSisi, 165);
        btnSisi.setBackground(GUI.ButtonBgBonusMenuClicked());
    }//GEN-LAST:event_btnSisiMousePressed

    private void btnSisiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSisiMouseReleased
        GUI.LiftButton(btnSisi, 163);
        btnSisi.setBackground(GUI.ButtonBgBonusMenuUnclicked());
    }//GEN-LAST:event_btnSisiMouseReleased

    private void btnSisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSisiActionPerformed
        CardLayout menu = (CardLayout) panelBody.getLayout();
        menu.show(panelBody, "sisi");
    }//GEN-LAST:event_btnSisiActionPerformed

    private void btnJarakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJarakMouseEntered
        GUI.DropButton(btnJarak, 323);
    }//GEN-LAST:event_btnJarakMouseEntered

    private void btnJarakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJarakMouseExited
        GUI.LiftButton(btnJarak, 320);
    }//GEN-LAST:event_btnJarakMouseExited

    private void btnJarakMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJarakMousePressed
        GUI.DropButton(btnJarak, 325);
        btnJarak.setBackground(GUI.ButtonBgBonusMenuClicked());
    }//GEN-LAST:event_btnJarakMousePressed

    private void btnJarakMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJarakMouseReleased
        GUI.LiftButton(btnJarak, 323);
        btnJarak.setBackground(GUI.ButtonBgBonusMenuUnclicked());
    }//GEN-LAST:event_btnJarakMouseReleased

    private void btnJarakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJarakActionPerformed
        CardLayout menu = (CardLayout) panelBody.getLayout();
        menu.show(panelBody, "jarak");
    }//GEN-LAST:event_btnJarakActionPerformed

    private void btnTambahSimpulMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahSimpulMouseEntered
        if(btnTambahSimpul.isEnabled()) {
            GUI.DropButton(btnTambahSimpul, 703);
        }
    }//GEN-LAST:event_btnTambahSimpulMouseEntered

    private void btnTambahSimpulMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahSimpulMouseExited
        if(btnTambahSimpul.isEnabled()) {
            GUI.LiftButton(btnTambahSimpul, 700);
        }
    }//GEN-LAST:event_btnTambahSimpulMouseExited

    private void btnTambahSimpulMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahSimpulMousePressed
        if(btnTambahSimpul.isEnabled()) {
            GUI.DropButton(btnTambahSimpul, 705);
        }
    }//GEN-LAST:event_btnTambahSimpulMousePressed

    private void btnTambahSimpulMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahSimpulMouseReleased
        if(btnTambahSimpul.isEnabled()) {
            GUI.LiftButton(btnTambahSimpul, 703);
        }
    }//GEN-LAST:event_btnTambahSimpulMouseReleased

    private void txtSimpulBaruKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSimpulBaruKeyReleased
        if("".equals(txtSimpulBaru.getText()) || "Masukkan nama simpul...".equals(txtSimpulBaru.getText()) || !GUI.ceknamasimpul(txtSimpulBaru.getText())) {
            areaInfoSimpul.setText("");
            if (!GUI.ceknamasimpul(txtSimpulBaru.getText())) {
                areaInfoSimpul.setText("Nama simpul tidak boleh sama dengan simpul yang ada!");
            }
            btnTambahSimpul.setEnabled(false);
        } else {
            areaInfoSimpul.setText("");
            btnTambahSimpul.setEnabled(true);
        } 
    }//GEN-LAST:event_txtSimpulBaruKeyReleased

    private void txtSimpulBaruFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSimpulBaruFocusGained
        if("Masukkan nama simpul...".equals(txtSimpulBaru.getText())) {
            txtSimpulBaru.setText("");
        }
    }//GEN-LAST:event_txtSimpulBaruFocusGained

    private void txtSimpulBaruFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSimpulBaruFocusLost
        if("".equals(txtSimpulBaru.getText())) {
            txtSimpulBaru.setText("Masukkan nama simpul...");
        }
    }//GEN-LAST:event_txtSimpulBaruFocusLost

    private void txtSimpulBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSimpulBaruActionPerformed
        if(!"".equals(txtSimpulBaru.getText()) && GUI.ceknamasimpul(txtSimpulBaru.getText())) {
            Graph.tambahSimpul(txtSimpulBaru.getText());
            GUI.UpdateCombobox();
            txtSimpulBaru.setText("");
            btnTambahSimpul.setIcon(Check);
            GUI.tambahsimpul.restart();
        }
    }//GEN-LAST:event_txtSimpulBaruActionPerformed

    private void txtInputSimpulPertamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputSimpulPertamaKeyReleased
        if("".equals(txtInputSimpulPertama.getText()) || "Masukkan nama simpul...".equals(txtInputSimpulPertama.getText())) {
            btnMulai.setEnabled(false);
            btnMulai.setText("NAMA TIDAK BOLEH KOSONG");
        } else {
            btnMulai.setEnabled(true);
            btnMulai.setText("BUAT");
        }
    }//GEN-LAST:event_txtInputSimpulPertamaKeyReleased

    private void txtInputSimpulPertamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputSimpulPertamaActionPerformed
        if(!"".equals(txtInputSimpulPertama.getText())) {
            Graph.tambahSimpul(txtInputSimpulPertama.getText());
            GUI.UpdateCombobox();
            CardLayout menu = (CardLayout) panelBody.getLayout();
            menu.show(panelBody, "next");
        }
    }//GEN-LAST:event_txtInputSimpulPertamaActionPerformed

    private void txtInputSimpulPertamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputSimpulPertamaFocusGained
        if("Masukkan nama simpul...".equals(txtInputSimpulPertama.getText())) {
            txtInputSimpulPertama.setText("");
        }
    }//GEN-LAST:event_txtInputSimpulPertamaFocusGained

    private void txtInputSimpulPertamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputSimpulPertamaFocusLost
        if("".equals(txtInputSimpulPertama.getText())) {
            txtInputSimpulPertama.setText("Masukkan nama simpul...");
        }
    }//GEN-LAST:event_txtInputSimpulPertamaFocusLost

    private void btnMulaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMulaiMouseEntered
        if(btnMulai.isEnabled()) {
            GUI.DropButton(btnMulai, 463);
        }
    }//GEN-LAST:event_btnMulaiMouseEntered

    private void btnMulaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMulaiMouseExited
        if(btnMulai.isEnabled()) {
            GUI.LiftButton(btnMulai, 460);
        }
    }//GEN-LAST:event_btnMulaiMouseExited

    private void btnMulaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMulaiMousePressed
        if(btnMulai.isEnabled()) {
            GUI.DropButton(btnMulai, 465);
        }
    }//GEN-LAST:event_btnMulaiMousePressed

    private void btnMulaiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMulaiMouseReleased
        if(btnMulai.isEnabled()) {
            GUI.LiftButton(btnMulai, 463);
        }
    }//GEN-LAST:event_btnMulaiMouseReleased

    private void btnMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulaiActionPerformed
        Graph.tambahSimpul(txtInputSimpulPertama.getText());
        GUI.UpdateCombobox();
        CardLayout menu = (CardLayout) panelBody.getLayout();
        lblJudulTutorial.setText("SELANJUTNYA...");
        menu.show(panelBody, "next");
    }//GEN-LAST:event_btnMulaiActionPerformed

    private void btnSimpulTutorialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpulTutorialMouseEntered
        GUI.DropButton(btnSimpul, 3);
        GUI.DropButton(btnSimpulTutorial, 93);
    }//GEN-LAST:event_btnSimpulTutorialMouseEntered

    private void btnSimpulTutorialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpulTutorialMouseExited
        GUI.LiftButton(btnSimpul, 0);
        GUI.LiftButtonAlt(btnSimpulTutorial, 90);
    }//GEN-LAST:event_btnSimpulTutorialMouseExited

    private void btnSimpulTutorialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpulTutorialMousePressed
        GUI.DropButton(btnSimpul, 5);
        GUI.DropButton(btnSimpulTutorial, 95);
        btnSimpulTutorial.setBackground(GUI.ButtonBgBonusMenuClicked());
        btnSimpul.setBackground(GUI.ButtonBgBonusMenuClicked());
    }//GEN-LAST:event_btnSimpulTutorialMousePressed

    private void btnSimpulTutorialMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpulTutorialMouseReleased
        GUI.LiftButton(btnSimpul, 3);
        GUI.LiftButtonAlt(btnSimpulTutorial, 93);
        btnSimpulTutorial.setBackground(GUI.ButtonBgBonusMenuUnclicked());
        btnSimpul.setBackground(GUI.ButtonBgBonusMenuUnclicked());
    }//GEN-LAST:event_btnSimpulTutorialMouseReleased

    private void btnSimpulTutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpulTutorialActionPerformed
        CardLayout menu = (CardLayout) panelBody.getLayout();
        menu.show(panelBody, "simpul");
    }//GEN-LAST:event_btnSimpulTutorialActionPerformed

    private void btnSisiTutorialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSisiTutorialMouseEntered
        GUI.DropButton(btnSisi, 163);
        GUI.DropButton(btnSisiTutorial, 93);
    }//GEN-LAST:event_btnSisiTutorialMouseEntered

    private void btnSisiTutorialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSisiTutorialMouseExited
        GUI.LiftButton(btnSisi, 160);
        GUI.LiftButtonAlt(btnSisiTutorial, 90);
    }//GEN-LAST:event_btnSisiTutorialMouseExited

    private void btnSisiTutorialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSisiTutorialMousePressed
        GUI.DropButton(btnSisi, 165);
        GUI.DropButton(btnSisiTutorial, 95);
        btnSisiTutorial.setBackground(GUI.ButtonBgBonusMenuClicked());
        btnSisi.setBackground(GUI.ButtonBgBonusMenuClicked());
    }//GEN-LAST:event_btnSisiTutorialMousePressed

    private void btnSisiTutorialMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSisiTutorialMouseReleased
        GUI.LiftButton(btnSisi, 163);
        GUI.LiftButtonAlt(btnSisiTutorial, 93);
        btnSisiTutorial.setBackground(GUI.ButtonBgBonusMenuUnclicked());
        btnSisi.setBackground(GUI.ButtonBgBonusMenuUnclicked());
    }//GEN-LAST:event_btnSisiTutorialMouseReleased

    private void btnSisiTutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSisiTutorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSisiTutorialActionPerformed

    private void btnJarakTutorialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJarakTutorialMouseEntered
        GUI.DropButton(btnJarak, 323);
        GUI.DropButton(btnJarakTutorial, 93);
    }//GEN-LAST:event_btnJarakTutorialMouseEntered

    private void btnJarakTutorialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJarakTutorialMouseExited
        GUI.LiftButton(btnJarak, 320);
        GUI.LiftButtonAlt(btnJarakTutorial, 90);
    }//GEN-LAST:event_btnJarakTutorialMouseExited

    private void btnJarakTutorialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJarakTutorialMousePressed
        GUI.DropButton(btnJarak, 325);
        GUI.DropButton(btnJarakTutorial, 95);
        btnJarakTutorial.setBackground(GUI.ButtonBgBonusMenuClicked());
        btnJarak.setBackground(GUI.ButtonBgBonusMenuClicked());
    }//GEN-LAST:event_btnJarakTutorialMousePressed

    private void btnJarakTutorialMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJarakTutorialMouseReleased
        GUI.LiftButton(btnJarak, 323);
        GUI.LiftButtonAlt(btnJarakTutorial, 93);
        btnJarakTutorial.setBackground(GUI.ButtonBgBonusMenuUnclicked());
        btnJarak.setBackground(GUI.ButtonBgBonusMenuUnclicked());
    }//GEN-LAST:event_btnJarakTutorialMouseReleased

    private void btnJarakTutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJarakTutorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJarakTutorialActionPerformed

    private void btnTambahSisiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahSisiMouseEntered
        if (btnTambahSisi.isEnabled()) {
            GUI.DropButton(btnTambahSisi, 603);
        }
    }//GEN-LAST:event_btnTambahSisiMouseEntered

    private void btnTambahSisiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahSisiMouseExited
        GUI.LiftButton(btnTambahSisi, 600);
    }//GEN-LAST:event_btnTambahSisiMouseExited

    private void btnTambahSisiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahSisiMousePressed
        if (btnTambahSisi.isEnabled()) {
            GUI.DropButton(btnTambahSisi, 605);
        }
    }//GEN-LAST:event_btnTambahSisiMousePressed

    private void btnTambahSisiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahSisiMouseReleased
        GUI.LiftButton(btnTambahSisi, 603);
    }//GEN-LAST:event_btnTambahSisiMouseReleased

    private void txtInputJarakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputJarakActionPerformed
        int start = cmbxTitikAwal.getSelectedIndex();
        int end = cmbxTitikAkhir.getSelectedIndex();
        int jrk;
        if ("".equals(txtInputJarak.getText())){
            jrk = 0;
        } else {
            jrk = Integer.parseInt(txtInputJarak.getText());
        }
        boolean duaarah = ToggleDuaArah.isSelected();
        
        txtInputJarak.setText("");
        if (start != -1 || end != -1) {
            Graph.tambahSisi(0, start, end, jrk, duaarah);
        }
    }//GEN-LAST:event_txtInputJarakActionPerformed

    private void txtInputJarakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputJarakKeyReleased
        if(!"".equals(txtInputJarak.getText())) {
            btnTambahSisi.setEnabled(true);
        } else {
            btnTambahSisi.setEnabled(false);
        }
    }//GEN-LAST:event_txtInputJarakKeyReleased

    private void txtInputJarakFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputJarakFocusGained
        if("0".equals(txtInputJarak.getText())) {
            txtInputJarak.setText("");
        }
    }//GEN-LAST:event_txtInputJarakFocusGained

    private void txtInputJarakFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputJarakFocusLost
        if("".equals(txtInputJarak.getText())) {
            txtInputJarak.setText("0");
        }
    }//GEN-LAST:event_txtInputJarakFocusLost

    private void cmbxTitikAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxTitikAwalActionPerformed
        int start = cmbxTitikAwal.getSelectedIndex();
        int end = cmbxTitikAkhir.getSelectedIndex();
        
        if (start == end) {
            txtInputJarak.setEditable(false);
            btnTambahSimpul.setEnabled(false);
            txtInputJarak.setText("JARAK TIDAK ADA");
        } else if (Graph.adjM.get(start).get(end) != 1000000000){
            txtInputJarak.setEditable(true);
            txtInputJarak.setText(Integer.toString(Graph.adjM.get(start).get(end)));
        } else {
            txtInputJarak.setEditable(true);
            txtInputJarak.setText("0");
        }
    }//GEN-LAST:event_cmbxTitikAwalActionPerformed

    private void cmbxTitikAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxTitikAkhirActionPerformed
        int start = cmbxTitikAwal.getSelectedIndex();
        int end = cmbxTitikAkhir.getSelectedIndex();
        
        if (start == end) {
            txtInputJarak.setEditable(false);
            btnTambahSimpul.setEnabled(false);
            txtInputJarak.setText("JARAK TIDAK ADA");
        } else if (Graph.adjM.get(start).get(end) != 1000000000){
            txtInputJarak.setEditable(true);
            txtInputJarak.setText(Integer.toString(Graph.adjM.get(start).get(end)));
        } else {
            txtInputJarak.setEditable(true);
            txtInputJarak.setText("0");
        }
    }//GEN-LAST:event_cmbxTitikAkhirActionPerformed

    private void ToggleDuaArahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleDuaArahActionPerformed
        if (ToggleDuaArah.isSelected()) {
            ToggleDuaArah.setIcon(TwoWay);
        } else {
            ToggleDuaArah.setIcon(OneWay);
        }
    }//GEN-LAST:event_ToggleDuaArahActionPerformed

    private void cmbxStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxStartActionPerformed
        int start = cmbxStart.getSelectedIndex();
        int end = cmbxEnd.getSelectedIndex();
        
        areaInfoJarak.setText("");
        if (start == end) {
            areaInfoJarak.setText("Tidak dapat mencari jarak simpul ke dirinya sendiri");
        } else {
            Graph.carijarak(start);
            Graph.carijalan(start, end);
            if (Graph.jarakfinal != 1000000000) {
                areaInfoJarak.append("Jarak dari simpul " + Graph.simpul.get(start).nama + " dan simpul " + Graph.simpul.get(end).nama + " adalah " + Graph.jarakfinal + "\n");
                areaInfoJarak.append("Jalur yang dilewati: ");
                for (int n : Graph.jalur) {
                    if (n != start) {
                        areaInfoJarak.append(" - ");
                    }
                    areaInfoJarak.append(Graph.simpul.get(n).nama);
                }
            } else {
                areaInfoJarak.setText("Simpul " + Graph.simpul.get(end).nama + " tidak dapat dicapai dari simpul " + Graph.simpul.get(start).nama);
            }
        }
    }//GEN-LAST:event_cmbxStartActionPerformed

    private void cmbxEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxEndActionPerformed
        int start = cmbxStart.getSelectedIndex();
        int end = cmbxEnd.getSelectedIndex();
        
        areaInfoJarak.setText("");
        if (start == end) {
            areaInfoJarak.setText("Tidak dapat mencari jarak simpul ke dirinya sendiri");
        } else {
            Graph.carijarak(start);
            Graph.carijalan(start, end);
            if (Graph.jarakfinal != 1000000000) {
                areaInfoJarak.append("Jarak dari simpul " + Graph.simpul.get(start).nama + " dan simpul " + Graph.simpul.get(end).nama + " adalah " + Graph.jarakfinal + "\n");
                areaInfoJarak.append("Jalur yang dilewati: ");
                for (int n : Graph.jalur) {
                    if (n != start) {
                        areaInfoJarak.append(" - ");
                    }
                    areaInfoJarak.append(Graph.simpul.get(n).nama);
                }
            } else {
                areaInfoJarak.setText("Simpul " + Graph.simpul.get(end).nama + " tidak dapat dicapai dari simpul " + Graph.simpul.get(start).nama);
            }
        }
    }//GEN-LAST:event_cmbxEndActionPerformed

    private void btnHelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseEntered
        GUI.DropButton(btnHelp, 483);
    }//GEN-LAST:event_btnHelpMouseEntered

    private void btnHelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseExited
        GUI.LiftButton(btnHelp, 480);
    }//GEN-LAST:event_btnHelpMouseExited

    private void btnHelpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMousePressed
        GUI.DropButton(btnHelp, 485);
    }//GEN-LAST:event_btnHelpMousePressed

    private void btnHelpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseReleased
        GUI.LiftButton(btnHelp, 483);
    }//GEN-LAST:event_btnHelpMouseReleased

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        CardLayout menu = (CardLayout) panelBody.getLayout();
        lblJudulTutorial.setText("BANTUAN");
        menu.show(panelBody, "next");
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnMoveBonusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoveBonusMouseEntered
        GUI.DropButton(btnMoveBonus, 733);
    }//GEN-LAST:event_btnMoveBonusMouseEntered

    private void btnMoveBonusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoveBonusMouseExited
        GUI.LiftButton(btnMoveBonus, 730);
    }//GEN-LAST:event_btnMoveBonusMouseExited

    private void btnMoveBonusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoveBonusMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
        GUI.DropButton(btnMoveBonus, 735);
        btnMoveBonus.setBackground(GUI.ButtonBgClicked());
        btnMoveBonus.setCursor(new Cursor(MOVE_CURSOR));
    }//GEN-LAST:event_btnMoveBonusMousePressed

    private void btnMoveBonusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoveBonusMouseReleased
        GUI.LiftButton(btnMoveBonus, 733);
        btnMoveBonus.setBackground(GUI.ButtonBgUnclicked());
        btnMoveBonus.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnMoveBonusMouseReleased

    private void btnMoveBonusMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoveBonusMouseDragged
        this.setLocation (evt.getXOnScreen() - xMouse - btnMoveBonus.getX(), evt.getYOnScreen() - yMouse - btnMoveBonus.getY());
    }//GEN-LAST:event_btnMoveBonusMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrafBonus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrafBonus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrafBonus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrafBonus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrafBonus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ToggleDuaArah;
    private javax.swing.JTextArea areaInfoJarak;
    private javax.swing.JTextArea areaInfoSimpul;
    public static javax.swing.JButton btnBack;
    public static javax.swing.JButton btnExit;
    public static javax.swing.JButton btnHelp;
    public static javax.swing.JButton btnJarak;
    public static javax.swing.JButton btnJarakTutorial;
    private javax.swing.JButton btnMoveBonus;
    private javax.swing.JButton btnMulai;
    public static javax.swing.JButton btnSimpul;
    public static javax.swing.JButton btnSimpulTutorial;
    public static javax.swing.JButton btnSisi;
    public static javax.swing.JButton btnSisiTutorial;
    public static javax.swing.JButton btnTambahSimpul;
    public static javax.swing.JButton btnTambahSisi;
    public static javax.swing.JComboBox<String> cmbxEnd;
    public static javax.swing.JComboBox<String> cmbxLihatSimpul;
    public static javax.swing.JComboBox<String> cmbxStart;
    public static javax.swing.JComboBox<String> cmbxTitikAkhir;
    public static javax.swing.JComboBox<String> cmbxTitikAwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAkhir;
    private javax.swing.JLabel lblAwal;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblInfoJarak;
    private javax.swing.JLabel lblInfoSimpul;
    private javax.swing.JLabel lblInputJarak;
    private javax.swing.JLabel lblInputSimpul;
    private javax.swing.JLabel lblInputSimpulPertama;
    private javax.swing.JLabel lblJarak;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudulBuatSimpul;
    private javax.swing.JLabel lblJudulJarak;
    private javax.swing.JLabel lblJudulSimpul;
    private javax.swing.JLabel lblJudulSisi;
    private javax.swing.JLabel lblJudulTutorial;
    private javax.swing.JLabel lblSimpulBaru;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblSubJudul;
    private javax.swing.JPanel panelAwal;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelJarak;
    private javax.swing.JPanel panelSimpul;
    private javax.swing.JPanel panelSisi;
    private javax.swing.JPanel panelTutorial;
    private javax.swing.JLabel shBody;
    private javax.swing.JLabel shBtnBack;
    private javax.swing.JLabel shBtnExit;
    private javax.swing.JLabel shBtnHelp;
    private javax.swing.JLabel shBtnJarak;
    private javax.swing.JLabel shBtnJarakTutorial;
    private javax.swing.JLabel shBtnMoveBonus;
    private javax.swing.JLabel shBtnMulai;
    private javax.swing.JLabel shBtnSimpul;
    private javax.swing.JLabel shBtnSimpulTutorial;
    private javax.swing.JLabel shBtnSisi;
    private javax.swing.JLabel shBtnSisiTutorial;
    private javax.swing.JLabel shBtnTambahSimpul;
    private javax.swing.JLabel shBtnTambahSisi;
    private javax.swing.JLabel shInfoJarak;
    private javax.swing.JLabel shInfoSimpul;
    private javax.swing.JLabel shInputSimpulPertama;
    private javax.swing.JLabel shLblInputJarak;
    private javax.swing.JLabel shLblSimpulBaru;
    private javax.swing.JLabel shToggleOneWay;
    private javax.swing.JTextField txtInputJarak;
    private javax.swing.JTextField txtInputSimpulPertama;
    private javax.swing.JTextField txtSimpulBaru;
    // End of variables declaration//GEN-END:variables
}
