/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graph;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Edho
 */
public class Maps extends javax.swing.JFrame {

    Graph G;
    static JLabel[] Pin;
    static JLabel[] Jalur;
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    static ImageIcon PinTransparent;
    static ImageIcon PinOpaque;
    int xMouse;
    int yMouse;
    public Maps() {
        initComponents();
        G = new Graph();
        PinOpaque = new javax.swing.ImageIcon(getClass().getResource("/Assets/Pin.png"));
        PinTransparent = new javax.swing.ImageIcon(getClass().getResource("/Assets/PinTransparency.png"));
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        Pin = new JLabel[]{Pin0, Pin1, Pin2, Pin3, Pin4, Pin5, Pin6, Pin7, Pin8, Pin9, Pin10, Pin11, Pin12, Pin13, Pin14};
        Jalur = new JLabel[]{Jalur0, Jalur1, Jalur2, Jalur3, Jalur4, Jalur5, Jalur6, Jalur7, Jalur8, Jalur9, Jalur10, Jalur11, Jalur12, Jalur13, Jalur14, Jalur15, Jalur16, Jalur17, Jalur18, Jalur19, Jalur20, Jalur21, Jalur22, Jalur23, Jalur24};
        btnCancel.setVisible(false);
        shBtnCancel.setVisible(false);
        GUI.ResetOverlayJalur(false);
        G.preload();
        this.setIconImage(PinOpaque.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        btnGeserMaps = new javax.swing.JButton();
        shBtnGeserMaps = new javax.swing.JLabel();
        btnBonus = new javax.swing.JButton();
        shBtnBonus = new javax.swing.JLabel();
        btnAbout = new javax.swing.JButton();
        shBtnAbout = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        lblPintuTolAwal = new javax.swing.JLabel();
        shLblPintuTolAwal = new javax.swing.JLabel();
        lblPintuTolAkhir = new javax.swing.JLabel();
        shLblPintuTolAkhir = new javax.swing.JLabel();
        lblKe = new javax.swing.JLabel();
        lblJarak = new javax.swing.JLabel();
        shLblJarak = new javax.swing.JLabel();
        panelInfoWaktuTempuh = new javax.swing.JPanel();
        panelWaktuTempuh = new javax.swing.JPanel();
        lblWaktuTempuh = new javax.swing.JLabel();
        panelUbahSpeed = new javax.swing.JPanel();
        lblSpeed = new javax.swing.JLabel();
        slSpeed = new javax.swing.JSlider();
        shLblWaktuTempuh = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        shBtnCancel = new javax.swing.JLabel();
        panelMap = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Pin0 = new javax.swing.JLabel();
        Pin1 = new javax.swing.JLabel();
        Pin2 = new javax.swing.JLabel();
        Pin3 = new javax.swing.JLabel();
        Pin4 = new javax.swing.JLabel();
        Pin5 = new javax.swing.JLabel();
        Pin6 = new javax.swing.JLabel();
        Pin7 = new javax.swing.JLabel();
        Pin8 = new javax.swing.JLabel();
        Pin9 = new javax.swing.JLabel();
        Pin10 = new javax.swing.JLabel();
        Pin11 = new javax.swing.JLabel();
        Pin12 = new javax.swing.JLabel();
        Pin13 = new javax.swing.JLabel();
        Pin14 = new javax.swing.JLabel();
        Jalur0 = new javax.swing.JLabel();
        Jalur1 = new javax.swing.JLabel();
        Jalur2 = new javax.swing.JLabel();
        Jalur3 = new javax.swing.JLabel();
        Jalur4 = new javax.swing.JLabel();
        Jalur5 = new javax.swing.JLabel();
        Jalur6 = new javax.swing.JLabel();
        Jalur7 = new javax.swing.JLabel();
        Jalur8 = new javax.swing.JLabel();
        Jalur9 = new javax.swing.JLabel();
        Jalur10 = new javax.swing.JLabel();
        Jalur11 = new javax.swing.JLabel();
        Jalur12 = new javax.swing.JLabel();
        Jalur13 = new javax.swing.JLabel();
        Jalur14 = new javax.swing.JLabel();
        Jalur15 = new javax.swing.JLabel();
        Jalur16 = new javax.swing.JLabel();
        Jalur17 = new javax.swing.JLabel();
        Jalur18 = new javax.swing.JLabel();
        Jalur19 = new javax.swing.JLabel();
        Jalur20 = new javax.swing.JLabel();
        Jalur21 = new javax.swing.JLabel();
        Jalur22 = new javax.swing.JLabel();
        Jalur23 = new javax.swing.JLabel();
        Jalur24 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        shBtnExit = new javax.swing.JLabel();
        Map = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setOpaque(false);
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGeserMaps.setBackground(new java.awt.Color(240, 215, 97));
        btnGeserMaps.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnGeserMaps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Move.png"))); // NOI18N
        btnGeserMaps.setContentAreaFilled(false);
        btnGeserMaps.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGeserMaps.setOpaque(true);
        btnGeserMaps.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnGeserMapsMouseDragged(evt);
            }
        });
        btnGeserMaps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGeserMapsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGeserMapsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGeserMapsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnGeserMapsMouseReleased(evt);
            }
        });
        panelMenu.add(btnGeserMaps, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 70, 70));

        shBtnGeserMaps.setBackground(new java.awt.Color(0, 0, 0));
        shBtnGeserMaps.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shBtnGeserMaps.setOpaque(true);
        panelMenu.add(shBtnGeserMaps, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 5, 70, 70));

        btnBonus.setBackground(new java.awt.Color(240, 215, 97));
        btnBonus.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnBonus.setText("BONUS");
        btnBonus.setContentAreaFilled(false);
        btnBonus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBonus.setOpaque(true);
        btnBonus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBonusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBonusMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBonusMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBonusMouseReleased(evt);
            }
        });
        btnBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBonusActionPerformed(evt);
            }
        });
        panelMenu.add(btnBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 50));

        shBtnBonus.setBackground(new java.awt.Color(0, 0, 0));
        shBtnBonus.setOpaque(true);
        panelMenu.add(shBtnBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 95, 160, 50));

        btnAbout.setBackground(new java.awt.Color(240, 215, 97));
        btnAbout.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnAbout.setText("ABOUT");
        btnAbout.setContentAreaFilled(false);
        btnAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbout.setOpaque(true);
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAboutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAboutMouseReleased(evt);
            }
        });
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        panelMenu.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 50));

        shBtnAbout.setBackground(new java.awt.Color(0, 0, 0));
        shBtnAbout.setOpaque(true);
        panelMenu.add(shBtnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 165, 160, 50));

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 190, 230));

        panelInfo.setOpaque(false);
        panelInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPintuTolAwal.setBackground(new java.awt.Color(240, 215, 97));
        lblPintuTolAwal.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblPintuTolAwal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPintuTolAwal.setText("???");
        lblPintuTolAwal.setOpaque(true);
        panelInfo.add(lblPintuTolAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 50));

        shLblPintuTolAwal.setBackground(new java.awt.Color(151, 136, 61));
        shLblPintuTolAwal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shLblPintuTolAwal.setOpaque(true);
        panelInfo.add(shLblPintuTolAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 160, 50));

        lblPintuTolAkhir.setBackground(new java.awt.Color(240, 215, 97));
        lblPintuTolAkhir.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblPintuTolAkhir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPintuTolAkhir.setText("???");
        lblPintuTolAkhir.setOpaque(true);
        panelInfo.add(lblPintuTolAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 160, 50));

        shLblPintuTolAkhir.setBackground(new java.awt.Color(151, 136, 61));
        shLblPintuTolAkhir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shLblPintuTolAkhir.setOpaque(true);
        panelInfo.add(shLblPintuTolAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 25, 160, 50));

        lblKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/To-Arrow.png"))); // NOI18N
        panelInfo.add(lblKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 30, 32, 32));

        lblJarak.setBackground(new java.awt.Color(240, 215, 97));
        lblJarak.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblJarak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJarak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Road.png"))); // NOI18N
        lblJarak.setOpaque(true);
        panelInfo.add(lblJarak, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, 70));

        shLblJarak.setBackground(new java.awt.Color(151, 136, 61));
        shLblJarak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shLblJarak.setOpaque(true);
        panelInfo.add(shLblJarak, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 95, 180, 70));

        panelInfoWaktuTempuh.setBackground(new java.awt.Color(240, 215, 97));
        panelInfoWaktuTempuh.setLayout(new java.awt.CardLayout());

        panelWaktuTempuh.setBackground(new java.awt.Color(240, 215, 97));
        panelWaktuTempuh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelWaktuTempuhMouseEntered(evt);
            }
        });
        panelWaktuTempuh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWaktuTempuh.setBackground(new java.awt.Color(240, 215, 97));
        lblWaktuTempuh.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblWaktuTempuh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWaktuTempuh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Clock.png"))); // NOI18N
        lblWaktuTempuh.setOpaque(true);
        panelWaktuTempuh.add(lblWaktuTempuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 70));

        panelInfoWaktuTempuh.add(panelWaktuTempuh, "info");

        panelUbahSpeed.setBackground(new java.awt.Color(240, 215, 97));
        panelUbahSpeed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelUbahSpeedMouseExited(evt);
            }
        });
        panelUbahSpeed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSpeed.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblSpeed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSpeed.setText("60 km/j");
        lblSpeed.setToolTipText("");
        panelUbahSpeed.add(lblSpeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 180, 30));

        slSpeed.setMaximum(110);
        slSpeed.setMinimum(10);
        slSpeed.setValue(60);
        slSpeed.setOpaque(false);
        slSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slSpeedStateChanged(evt);
            }
        });
        panelUbahSpeed.add(slSpeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, -1));

        panelInfoWaktuTempuh.add(panelUbahSpeed, "ubah");

        panelInfo.add(panelInfoWaktuTempuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 180, 70));

        shLblWaktuTempuh.setBackground(new java.awt.Color(151, 136, 61));
        shLblWaktuTempuh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shLblWaktuTempuh.setOpaque(true);
        panelInfo.add(shLblWaktuTempuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 95, 180, 70));

        btnCancel.setBackground(new java.awt.Color(255, 60, 0));
        btnCancel.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Cross.png"))); // NOI18N
        btnCancel.setContentAreaFilled(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setOpaque(true);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelMouseReleased(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        panelInfo.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 50, 140));

        shBtnCancel.setBackground(new java.awt.Color(158, 37, 0));
        shBtnCancel.setOpaque(true);
        panelInfo.add(shBtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 25, 50, 140));

        getContentPane().add(panelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 510, 180));

        panelMap.setPreferredSize(new java.awt.Dimension(900, 808));
        panelMap.setLayout(new java.awt.CardLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pin0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/PinTransparency.png"))); // NOI18N
        Pin0.setToolTipText("Gerbang Tol Serpong");
        Pin0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pin0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pin0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pin0MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pin0MousePressed(evt);
            }
        });
        jPanel3.add(Pin0, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, -1, -1));

        Pin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/PinTransparency.png"))); // NOI18N
        Pin1.setToolTipText("Gerbang Tol Pluit");
        Pin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pin1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pin1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pin1MousePressed(evt);
            }
        });
        jPanel3.add(Pin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        Pin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/PinTransparency.png"))); // NOI18N
        Pin2.setToolTipText("Gerbang Tol Tanjung Priok");
        Pin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pin2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pin2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pin2MousePressed(evt);
            }
        });
        jPanel3.add(Pin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 120, -1, -1));

        Pin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/PinTransparency.png"))); // NOI18N
        Pin3.setToolTipText("Gerbang Tol Meruya");
        Pin3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pin3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pin3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pin3MousePressed(evt);
            }
        });
        jPanel3.add(Pin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        Pin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/PinTransparency.png"))); // NOI18N
        Pin4.setToolTipText("Gerbang Tol Tomang");
        Pin4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pin4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pin4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pin4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pin4MousePressed(evt);
            }
        });
        jPanel3.add(Pin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 245, -1, -1));

        Pin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/PinTransparency.png"))); // NOI18N
        Pin5.setToolTipText("Gerbang Tol Pulomas");
        Pin5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pin5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pin5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pin5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pin5MousePressed(evt);
            }
        });
        jPanel3.add(Pin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));

        Pin6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/PinTransparency.png"))); // NOI18N
        Pin6.setToolTipText("Pintu Tol Cakung Timur");
        Pin6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pin6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pin6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pin6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pin6MousePressed(evt);
            }
        });
        jPanel3.add(Pin6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, -1, -1));

        Pin7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/PinTransparency.png"))); // NOI18N
        Pin7.setToolTipText("Gerbang Tol Pejompongan");
        Pin7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pin7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pin7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pin7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pin7MousePressed(evt);
            }
        });
        jPanel3.add(Pin7, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 310, 30, 40));

        Pin8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/PinTransparency.png"))); // NOI18N
        Pin8.setToolTipText("Gerbang Tol Senayan");
        Pin8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pin8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pin8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pin8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pin8MousePressed(evt);
            }
        });
        jPanel3.add(Pin8, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 335, -1, -1));

        Pin9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/PinTransparency.png"))); // NOI18N
        Pin9.setToolTipText("Gerbang Tol Veteran");
        Pin9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pin9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pin9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pin9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pin9MousePressed(evt);
            }
        });
        jPanel3.add(Pin9, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 430, -1, -1));

        Pin10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/PinTransparency.png"))); // NOI18N
        Pin10.setToolTipText("Gerbang Tol Cawang");
        Pin10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pin10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pin10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pin10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pin10MousePressed(evt);
            }
        });
        jPanel3.add(Pin10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        Pin11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/PinTransparency.png"))); // NOI18N
        Pin11.setToolTipText("Gerbang Tol Halim Utama");
        Pin11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pin11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pin11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pin11MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pin11MousePressed(evt);
            }
        });
        jPanel3.add(Pin11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, -1, -1));

        Pin12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/PinTransparency.png"))); // NOI18N
        Pin12.setToolTipText("Gerbang Tol Cikunir");
        Pin12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pin12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pin12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pin12MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pin12MousePressed(evt);
            }
        });
        jPanel3.add(Pin12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, -1, -1));

        Pin13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/PinTransparency.png"))); // NOI18N
        Pin13.setToolTipText("Gerbang Tol Ciputat");
        Pin13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pin13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pin13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pin13MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pin13MousePressed(evt);
            }
        });
        jPanel3.add(Pin13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, -1, -1));

        Pin14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/PinTransparency.png"))); // NOI18N
        Pin14.setToolTipText("Gerbang Tol Dukuh");
        Pin14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pin14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pin14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pin14MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pin14MousePressed(evt);
            }
        });
        jPanel3.add(Pin14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, -1, -1));

        Jalur0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur00.png"))); // NOI18N
        jPanel3.add(Jalur0, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 125, -1, -1));

        Jalur1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur01.png"))); // NOI18N
        jPanel3.add(Jalur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 90, -1, -1));

        Jalur2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur02.png"))); // NOI18N
        jPanel3.add(Jalur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 112, -1, -1));

        Jalur3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur03.png"))); // NOI18N
        jPanel3.add(Jalur3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 112, -1, -1));

        Jalur4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur04.png"))); // NOI18N
        jPanel3.add(Jalur4, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 135, -1, -1));

        Jalur5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur05.png"))); // NOI18N
        jPanel3.add(Jalur5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 278, -1, -1));

        Jalur6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur06.png"))); // NOI18N
        jPanel3.add(Jalur6, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 457, -1, -1));

        Jalur7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur07.png"))); // NOI18N
        jPanel3.add(Jalur7, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 270, -1, -1));

        Jalur8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur08.png"))); // NOI18N
        jPanel3.add(Jalur8, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 343, -1, -1));

        Jalur9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur09.png"))); // NOI18N
        jPanel3.add(Jalur9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        Jalur10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur10.png"))); // NOI18N
        jPanel3.add(Jalur10, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 272, -1, -1));

        Jalur11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur11.png"))); // NOI18N
        jPanel3.add(Jalur11, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 277, -1, -1));

        Jalur12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur12.png"))); // NOI18N
        jPanel3.add(Jalur12, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 278, -1, -1));

        Jalur13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur13.png"))); // NOI18N
        jPanel3.add(Jalur13, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 368, -1, -1));

        Jalur14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur14.png"))); // NOI18N
        jPanel3.add(Jalur14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 439, -1, -1));

        Jalur15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur15.png"))); // NOI18N
        jPanel3.add(Jalur15, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 467, -1, -1));

        Jalur16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur16.png"))); // NOI18N
        jPanel3.add(Jalur16, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 277, -1, -1));

        Jalur17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur17.png"))); // NOI18N
        jPanel3.add(Jalur17, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 436, -1, -1));

        Jalur18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur18.png"))); // NOI18N
        jPanel3.add(Jalur18, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 438, -1, -1));

        Jalur19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur19.png"))); // NOI18N
        jPanel3.add(Jalur19, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 337, -1, -1));

        Jalur20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur20.png"))); // NOI18N
        jPanel3.add(Jalur20, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 338, -1, -1));

        Jalur21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur21.png"))); // NOI18N
        jPanel3.add(Jalur21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 535, -1, -1));

        Jalur22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur22.png"))); // NOI18N
        jPanel3.add(Jalur22, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 460, -1, -1));

        Jalur23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur23.png"))); // NOI18N
        jPanel3.add(Jalur23, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 436, -1, -1));

        Jalur24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Jalur24.png"))); // NOI18N
        jPanel3.add(Jalur24, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 303, -1, -1));

        btnExit.setBackground(new java.awt.Color(240, 215, 97));
        btnExit.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnExit.setText("KELUAR");
        btnExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExitMouseReleased(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel3.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 140, 50));

        shBtnExit.setBackground(new java.awt.Color(0, 0, 0));
        shBtnExit.setOpaque(true);
        jPanel3.add(shBtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 15, 140, 50));

        Map.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Map.png"))); // NOI18N
        jPanel3.add(Map, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 900, 810));

        panelMap.add(jPanel3, "card3");

        getContentPane().add(panelMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBonusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBonusMouseEntered
        GUI.DropButton(btnBonus, 13);
    }//GEN-LAST:event_btnBonusMouseEntered

    private void btnBonusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBonusMouseExited
        GUI.LiftButton(btnBonus, 10);
    }//GEN-LAST:event_btnBonusMouseExited

    private void btnBonusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBonusMousePressed
        GUI.DropButton(btnBonus, 15);
        btnBonus.setBackground(GUI.ButtonBgClicked());
    }//GEN-LAST:event_btnBonusMousePressed

    private void btnBonusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBonusMouseReleased
        GUI.LiftButton(btnBonus, 13);
        btnBonus.setBackground(GUI.ButtonBgUnclicked());
    }//GEN-LAST:event_btnBonusMouseReleased

    private void btnBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBonusActionPerformed
        G.flush();
        GrafBonus bonus = new GrafBonus();
        bonus.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBonusActionPerformed

    private void btnAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseEntered
        GUI.DropButton(btnAbout, 13);
    }//GEN-LAST:event_btnAboutMouseEntered

    private void btnAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseExited
        GUI.LiftButton(btnAbout, 10);
    }//GEN-LAST:event_btnAboutMouseExited

    private void btnAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMousePressed
        GUI.DropButton(btnAbout, 15);
        btnAbout.setBackground(GUI.ButtonBgClicked());
    }//GEN-LAST:event_btnAboutMousePressed

    private void btnAboutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseReleased
        GUI.LiftButton(btnAbout, 13);
        btnAbout.setBackground(GUI.ButtonBgUnclicked());
    }//GEN-LAST:event_btnAboutMouseReleased

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        Credits cred = new Credits();
        cred.previous = this;
        cred.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        GUI.DropButton(btnExit, 743);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        GUI.LiftButton(btnExit, 740);
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        if(GUI.confirmExit) {
            btnExit.setBackground(new Color(210,70,0));
        } else {
            btnExit.setBackground(GUI.ButtonBgClicked());
        }
        GUI.DropButton(btnExit, 745);
    }//GEN-LAST:event_btnExitMousePressed

    private void btnExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseReleased
        if (GUI.confirmExit) {
            btnExit.setBackground(new Color(255,60,0));
            btnExit.setForeground(new Color(255,255,255));
            shBtnExit.setBackground(new Color(158,37,0));
            
        } else {
            btnExit.setBackground(GUI.ButtonBgUnclicked());
        }
        GUI.LiftButton(btnExit, 743);
    }//GEN-LAST:event_btnExitMouseReleased

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        if (GUI.confirmExit) {
            System.exit(0);
        } else {
            btnExit.setText("KONFIRMASI?");
            GUI.confirmExit = true;
            GUI.exitmaps.restart();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        GUI.DropButton(btnCancel, 433);
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        GUI.LiftButton(btnCancel, 430);
    }//GEN-LAST:event_btnCancelMouseExited

    private void btnCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMousePressed
        btnCancel.setBackground(new Color(210,70,0));
        GUI.DropButton(btnCancel, 435);
    }//GEN-LAST:event_btnCancelMousePressed

    private void btnCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseReleased
        btnCancel.setBackground(new Color(255,60,0));
        GUI.LiftButton(btnCancel, 433);
    }//GEN-LAST:event_btnCancelMouseReleased

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        G.clearpinpoint();
        btnCancel.setVisible(false);
        shBtnCancel.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void Pin0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin0MouseEntered
        G.pinpointHover(0);
    }//GEN-LAST:event_Pin0MouseEntered

    private void Pin0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin0MouseExited
        G.pinpointUnhover(0);
    }//GEN-LAST:event_Pin0MouseExited

    private void Pin0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin0MousePressed
        G.pinpointClick(0);
    }//GEN-LAST:event_Pin0MousePressed

    private void Pin1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin1MouseEntered
        G.pinpointHover(1);
    }//GEN-LAST:event_Pin1MouseEntered

    private void Pin1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin1MouseExited
        G.pinpointUnhover(1);
    }//GEN-LAST:event_Pin1MouseExited

    private void Pin1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin1MousePressed
        G.pinpointClick(1);
    }//GEN-LAST:event_Pin1MousePressed

    private void Pin2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin2MouseEntered
        G.pinpointHover(2);
    }//GEN-LAST:event_Pin2MouseEntered

    private void Pin2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin2MouseExited
        G.pinpointUnhover(2);
    }//GEN-LAST:event_Pin2MouseExited

    private void Pin2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin2MousePressed
        G.pinpointClick(2);
    }//GEN-LAST:event_Pin2MousePressed

    private void Pin3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin3MouseEntered
        G.pinpointHover(3);
    }//GEN-LAST:event_Pin3MouseEntered

    private void Pin3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin3MouseExited
        G.pinpointUnhover(3);
    }//GEN-LAST:event_Pin3MouseExited

    private void Pin3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin3MousePressed
        G.pinpointClick(3);
    }//GEN-LAST:event_Pin3MousePressed

    private void Pin4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin4MouseEntered
        G.pinpointHover(4);
    }//GEN-LAST:event_Pin4MouseEntered

    private void Pin4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin4MouseExited
        G.pinpointUnhover(4);
    }//GEN-LAST:event_Pin4MouseExited

    private void Pin4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin4MousePressed
        G.pinpointClick(4);
    }//GEN-LAST:event_Pin4MousePressed

    private void Pin5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin5MouseEntered
        G.pinpointHover(5);
    }//GEN-LAST:event_Pin5MouseEntered

    private void Pin5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin5MouseExited
        G.pinpointUnhover(5);
    }//GEN-LAST:event_Pin5MouseExited

    private void Pin5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin5MousePressed
        G.pinpointClick(5);
    }//GEN-LAST:event_Pin5MousePressed

    private void Pin6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin6MouseEntered
        G.pinpointHover(6);
    }//GEN-LAST:event_Pin6MouseEntered

    private void Pin6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin6MouseExited
        G.pinpointUnhover(6);
    }//GEN-LAST:event_Pin6MouseExited

    private void Pin6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin6MousePressed
        G.pinpointClick(6);
    }//GEN-LAST:event_Pin6MousePressed

    private void Pin7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin7MouseEntered
        G.pinpointHover(7);
    }//GEN-LAST:event_Pin7MouseEntered

    private void Pin7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin7MouseExited
        G.pinpointUnhover(7);
    }//GEN-LAST:event_Pin7MouseExited

    private void Pin7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin7MousePressed
        G.pinpointClick(7);
    }//GEN-LAST:event_Pin7MousePressed

    private void Pin8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin8MouseEntered
        G.pinpointHover(8);
    }//GEN-LAST:event_Pin8MouseEntered

    private void Pin8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin8MouseExited
        G.pinpointUnhover(8);
    }//GEN-LAST:event_Pin8MouseExited

    private void Pin8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin8MousePressed
        G.pinpointClick(8);
    }//GEN-LAST:event_Pin8MousePressed

    private void Pin9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin9MouseEntered
        G.pinpointHover(9);
    }//GEN-LAST:event_Pin9MouseEntered

    private void Pin9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin9MouseExited
        G.pinpointUnhover(9);
    }//GEN-LAST:event_Pin9MouseExited

    private void Pin9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin9MousePressed
        G.pinpointClick(9);
    }//GEN-LAST:event_Pin9MousePressed

    private void Pin10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin10MouseEntered
        G.pinpointHover(10);
    }//GEN-LAST:event_Pin10MouseEntered

    private void Pin10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin10MouseExited
        G.pinpointUnhover(10);
    }//GEN-LAST:event_Pin10MouseExited

    private void Pin10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin10MousePressed
        G.pinpointClick(10);
    }//GEN-LAST:event_Pin10MousePressed

    private void Pin11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin11MouseEntered
        G.pinpointHover(11);
    }//GEN-LAST:event_Pin11MouseEntered

    private void Pin11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin11MouseExited
        G.pinpointUnhover(11);
    }//GEN-LAST:event_Pin11MouseExited

    private void Pin11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin11MousePressed
        G.pinpointClick(11);
    }//GEN-LAST:event_Pin11MousePressed

    private void Pin12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin12MouseEntered
        G.pinpointHover(12);
    }//GEN-LAST:event_Pin12MouseEntered

    private void Pin12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin12MouseExited
        G.pinpointUnhover(12);
    }//GEN-LAST:event_Pin12MouseExited

    private void Pin12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin12MousePressed
        G.pinpointClick(12);
    }//GEN-LAST:event_Pin12MousePressed

    private void Pin13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin13MouseEntered
        G.pinpointHover(13);
    }//GEN-LAST:event_Pin13MouseEntered

    private void Pin13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin13MouseExited
        G.pinpointUnhover(13);
    }//GEN-LAST:event_Pin13MouseExited

    private void Pin13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin13MousePressed
        G.pinpointClick(13);
    }//GEN-LAST:event_Pin13MousePressed

    private void Pin14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin14MouseEntered
        G.pinpointHover(14);
    }//GEN-LAST:event_Pin14MouseEntered

    private void Pin14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin14MouseExited
        G.pinpointUnhover(14);
    }//GEN-LAST:event_Pin14MouseExited

    private void Pin14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pin14MousePressed
        G.pinpointClick(14);
    }//GEN-LAST:event_Pin14MousePressed

    private void slSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slSpeedStateChanged
        lblSpeed.setText(Integer.toString(slSpeed.getValue()) + " km/j");
        Graph.cariwaktu();
    }//GEN-LAST:event_slSpeedStateChanged

    private void panelWaktuTempuhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelWaktuTempuhMouseEntered
        if(Graph.pinpoint) {
            CardLayout menu = (CardLayout) panelInfoWaktuTempuh.getLayout();
            menu.show(panelInfoWaktuTempuh, "ubah");
        }
    }//GEN-LAST:event_panelWaktuTempuhMouseEntered

    private void panelUbahSpeedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUbahSpeedMouseExited
        CardLayout menu = (CardLayout) panelInfoWaktuTempuh.getLayout();
        menu.show(panelInfoWaktuTempuh, "info");
    }//GEN-LAST:event_panelUbahSpeedMouseExited

    private void btnGeserMapsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGeserMapsMouseEntered
        GUI.DropButton(btnGeserMaps, 103);
    }//GEN-LAST:event_btnGeserMapsMouseEntered

    private void btnGeserMapsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGeserMapsMouseExited
        GUI.LiftButton(btnGeserMaps, 100);
    }//GEN-LAST:event_btnGeserMapsMouseExited

    private void btnGeserMapsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGeserMapsMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
        GUI.DropButton(btnGeserMaps, 105);
        btnGeserMaps.setBackground(GUI.ButtonBgClicked());
        btnGeserMaps.setCursor(new Cursor(MOVE_CURSOR));
    }//GEN-LAST:event_btnGeserMapsMousePressed

    private void btnGeserMapsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGeserMapsMouseReleased
        GUI.LiftButton(btnGeserMaps, 103);
        btnGeserMaps.setBackground(GUI.ButtonBgUnclicked());
        btnGeserMaps.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnGeserMapsMouseReleased

    private void btnGeserMapsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGeserMapsMouseDragged
        this.setLocation (evt.getXOnScreen() - xMouse - btnGeserMaps.getX() - panelMenu.getX(), evt.getYOnScreen() - yMouse - btnGeserMaps.getY() - panelMenu.getY());
    }//GEN-LAST:event_btnGeserMapsMouseDragged

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maps().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jalur0;
    private javax.swing.JLabel Jalur1;
    private javax.swing.JLabel Jalur10;
    private javax.swing.JLabel Jalur11;
    private javax.swing.JLabel Jalur12;
    private javax.swing.JLabel Jalur13;
    private javax.swing.JLabel Jalur14;
    private javax.swing.JLabel Jalur15;
    private javax.swing.JLabel Jalur16;
    private javax.swing.JLabel Jalur17;
    private javax.swing.JLabel Jalur18;
    private javax.swing.JLabel Jalur19;
    private javax.swing.JLabel Jalur2;
    private javax.swing.JLabel Jalur20;
    private javax.swing.JLabel Jalur21;
    private javax.swing.JLabel Jalur22;
    private javax.swing.JLabel Jalur23;
    private javax.swing.JLabel Jalur24;
    private javax.swing.JLabel Jalur3;
    private javax.swing.JLabel Jalur4;
    private javax.swing.JLabel Jalur5;
    private javax.swing.JLabel Jalur6;
    private javax.swing.JLabel Jalur7;
    private javax.swing.JLabel Jalur8;
    private javax.swing.JLabel Jalur9;
    private javax.swing.JLabel Map;
    private javax.swing.JLabel Pin0;
    private javax.swing.JLabel Pin1;
    private javax.swing.JLabel Pin10;
    private javax.swing.JLabel Pin11;
    private javax.swing.JLabel Pin12;
    public javax.swing.JLabel Pin13;
    private javax.swing.JLabel Pin14;
    private javax.swing.JLabel Pin2;
    private javax.swing.JLabel Pin3;
    private javax.swing.JLabel Pin4;
    private javax.swing.JLabel Pin5;
    public static javax.swing.JLabel Pin6;
    private javax.swing.JLabel Pin7;
    private javax.swing.JLabel Pin8;
    private javax.swing.JLabel Pin9;
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnBonus;
    public static javax.swing.JButton btnCancel;
    public static javax.swing.JButton btnExit;
    private javax.swing.JButton btnGeserMaps;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel lblJarak;
    private javax.swing.JLabel lblKe;
    public static javax.swing.JLabel lblPintuTolAkhir;
    public static javax.swing.JLabel lblPintuTolAwal;
    private javax.swing.JLabel lblSpeed;
    public static javax.swing.JLabel lblWaktuTempuh;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelInfoWaktuTempuh;
    private javax.swing.JPanel panelMap;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelUbahSpeed;
    private javax.swing.JPanel panelWaktuTempuh;
    private javax.swing.JLabel shBtnAbout;
    private javax.swing.JLabel shBtnBonus;
    public static javax.swing.JLabel shBtnCancel;
    public static javax.swing.JLabel shBtnExit;
    private javax.swing.JLabel shBtnGeserMaps;
    private javax.swing.JLabel shLblJarak;
    private javax.swing.JLabel shLblPintuTolAkhir;
    private javax.swing.JLabel shLblPintuTolAwal;
    private javax.swing.JLabel shLblWaktuTempuh;
    public static javax.swing.JSlider slSpeed;
    // End of variables declaration//GEN-END:variables
}
